app/Http/routes.php
<?php

Route::resource('users', 'UsersController', ['except' => ['show','destroy']]);
Route::post('users/{id}/destroy',['as' => 'users.destroy', 'uses' => 'UsersController@destroy']);

Route::get('api/{id}','UsersApiController@get');

app/Permission.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class Permission extends Model
{

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'permissions';

    protected $hidden = ['pivot'];
}

app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract
{
    use Authenticatable;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'email', 'password','surname'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password'];

    public function permissions(){
        return $this->belongsToMany('App\Permission', 'users_permissions', 'user_id', 'permission_id');
    }
}

app/UserPermission.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class UserPermission extends Model
{

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users_permissions';

    protected $fillable = ['user_id','permission_id'];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;

abstract class Controller extends BaseController
{
    use DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UsersApiController.php
<?php
/**
 * Created by PhpStorm.
 * User: Kuba
 * Date: 2015-08-04
 * Time: 12:56
 */

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\User;
use Response;

class UsersApiController extends Controller
{
    public function get($id)
    {
        $data = [];
        try {
            $data = User::with('permissions')->findOrFail($id);
            $code = 200;
        } catch (\Exception $e) {
            $code = 400;
            $data['error'] = $e->getMessage();
        }

        return Response::json($data, $code);
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Permission;
use App\User;
use Validator;
use Input;
use Redirect;
use Session;
use Response;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $users = User::all();

        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $permissions = Permission::all();

        return view('users.add', compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        $rules = [
            'name' => 'required|min:2',
            'surname' => 'required|min:2',
            'password' => 'required|min:6',
            'email' => 'required|email|unique:users,email'
        ];

        $validator = Validator::make($request->all(), $rules);

        if ($validator->fails()) {
            return Redirect::back()->withErrors($validator)->withInput($request->all());
        }

        $user = User::create($request->all());

        if($request->has('permissions')) {
            $user->permissions()->attach($request->get('permissions'));
        }

        Session::flash('flash_message', 'Success!');

        return Redirect::route('users.index');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        $permissions = Permission::all();
        $userPermissions = $user->permissions()->lists('permission_id')->toArray();

        return view('users.edit', compact('user', 'permissions', 'userPermissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request $request
     * @param  int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);

        $rules = [
            'name' => 'required|min:2',
            'surname' => 'required|min:2',
            'password' => 'required|min:6',
            'email' => 'required|email|unique:users,email,' . $id
        ];

        $validator = Validator::make($request->all(), $rules);

        if ($validator->fails()) {
            return Redirect::back()->withErrors($validator);
        }

        $user->fill($request->all())->save();

        if($request->has('permissions')) {
            $user->permissions()->sync($request->get('permissions'));
        }else{
            $user->permissions()->sync([]);
        }

        Session::flash('flash_message', 'Success!');

        return Redirect::back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        try {
            $user = User::findOrFail($id);

            $user->permissions()->detach();

            $user->delete();

            $code = 200;
        } catch (\Exception $e) {
            $code = 400;
        }

        return Response::json([], $code);
    }
}

resources/views/layouts/master.blade.php
<html>
    <head>
        <title>Zadanie testowe</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

        <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        @yield('scripts')
    </head>
    <body>
        <div class="container">
            @yield('content')
        </div>
    </body>
</html>

resources/views/users/add.blade.php
@extends('layouts.master')

@section('content')

    @if($errors->has())
        @foreach ($errors->all() as $error)
            <div class="alert alert-danger">{{ $error }}</div>
        @endforeach
    @endif

    {!! Form::open(['route' => 'users.store']) !!}

    <div class="form-group">
        {!! Form::label('name', 'Name:', ['class' => 'control-label']) !!}
        {!! Form::text('name', null, ['class' => 'form-control']) !!}
    </div>

    <div class="form-group">
        {!! Form::label('surname', 'Surname:', ['class' => 'control-label']) !!}
        {!! Form::text('surname', null, ['class' => 'form-control']) !!}
    </div>

    <div class="form-group">
        {!! Form::label('password', 'Password:', ['class' => 'control-label']) !!}
        {!! Form::password('password', ['class' => 'form-control']) !!}
    </div>

    <div class="form-group">
        {!! Form::label('email', 'Email:', ['class' => 'control-label']) !!}
        {!! Form::email('email', null, ['class' => 'form-control']) !!}
    </div>

    Permissions:<br>
    @foreach ($permissions as $permission)
        {!! Form::checkbox('permissions[]', $permission->id, null) !!}
        {{ $permission->name }}
        <br>
    @endforeach


    {!! Form::submit('Create user', ['class' => 'btn btn-primary']) !!}

    <a href="{!! route('users.index') !!}" class="btn btn-info">Back</a>

    {!! Form::close() !!}
@endsection

resources/views/users/edit.blade.php
@extends('layouts.master')

@section('content')

    @if(Session::has('flash_message'))
        <div class="alert alert-success">
            {{ Session::get('flash_message') }}
        </div>
    @endif

    @if($errors->has())
        @foreach ($errors->all() as $error)
            <div class="alert alert-danger">{{ $error }}</div>
        @endforeach
    @endif

    {!! Form::model($user,['method'=>'PATCH','route' => ['users.update',$user->id]]) !!}

    <div class="form-group">
        {!! Form::label('name', 'Name:', ['class' => 'control-label']) !!}
        {!! Form::text('name', null, ['class' => 'form-control']) !!}
    </div>

    <div class="form-group">
        {!! Form::label('surname', 'Surname:', ['class' => 'control-label']) !!}
        {!! Form::text('surname', null, ['class' => 'form-control']) !!}
    </div>

    <div class="form-group">
        {!! Form::label('password', 'Password:', ['class' => 'control-label']) !!}
        {!! Form::password('password', ['class' => 'form-control']) !!}
    </div>

    <div class="form-group">
        {!! Form::label('email', 'Email:', ['class' => 'control-label']) !!}
        {!! Form::email('email', null, ['class' => 'form-control']) !!}
    </div>

    Permissions:<br>
    @foreach ($permissions as $permission)
        {!! Form::checkbox('permissions[]', $permission->id, in_array($permission->id,$userPermissions)) !!}
        {{ $permission->name }}
        <br>
    @endforeach


    {!! Form::submit('Update user', ['class' => 'btn btn-primary']) !!}

    <a href="{!! route('users.index') !!}" class="btn btn-info">Back</a>

    {!! Form::close() !!}
@endsection

resources/views/users/index.blade.php
@extends('layouts.master')

@section('scripts')
    <script src="{{ asset('js/users.index.js') }}"></script>
@endsection

@section('content')

    @if(Session::has('flash_message'))
        <div class="alert alert-success">
            {{ Session::get('flash_message') }}
        </div>
    @endif

    <a href="{!! route('users.create') !!}" class="btn btn-info">Create</a>

    <table {!! (count($users)==0) ? 'style="display:none"' : '' !!} class="table table-bordered" id="userList">
        <thead>
            <th>Id</th>
            <th>Name</th>
            <th>Surname</th>
            <th>Email</th>
            <th>Action</th>
        </thead>
        <tbody>
    @foreach($users as $user)
        <tr>
            <td>{{ $user->id }}</td>
            <td>{{ $user->name }}</td>
            <td>{{ $user->surname }}</td>
            <td>{{ $user->email }}</td>
            <td>
                <a href="{{ route('users.edit',['id'=>$user->id]) }}" class="btn btn-info">Edit</a>
                <a href="#" data-url="{{ route('users.destroy',['id'=>$user->id]) }}" data-token="{{ Session::token() }}" class="btn btn-danger userDelete">Delete</a>
            </td>
        </tr>
    @endforeach
        </tbody>
    </table>
<div class="alert alert-warning" {!! (count($users)>0) ? 'style="display:none"' : '' !!} id="userListWarning">No users in database</div>

@endsection